### ISSUE TITLE
Dual contouring ?

### ISSUE THREAD

**Issue by aiekick** [Dmajster/dual_contouring#1]
Hello,

thanks to share your tech code.

btw are you sure it is the dual contouring algo ? for me its surfaceNets but not [dualcontouring](https://www.cse.wustl.edu/~taoju/research/dualContour.pdf)

**Comment by Dmajster** [comment]
Hi,

Yes in it's current state it only has the surface nets algorithm. I had plans to implement the QEF solver for a non-manifold dual contouring algorithm but haven't gotten around to it yet.

**Comment by aiekick** [comment]
ok, thanks. :)
